### PR TITLE
invalid opcode

### PR DESCRIPTION
**Pull request by 7flash**

### CODE REVIEW

**Comment by nadavhollander** [comment]
When `require(...)` fails, it throws a `revert` error, not an `invalid opcode` error.  Are you seeing something different locally?

**Comment by 7flash** [comment]
Truffle v4.0.3 (core: 4.0.3)
Solidity v0.4.18 (solc-js)
Before this commit test fails because it expected "invalid opcode" to be equal "revert"

**Comment by 7flash** [comment]
Which version are you using?

**Comment by nadavhollander** [comment]
The `REVERT` opcode was added with Byzantium (see [here](https://github.com/trufflesuite/ganache-cli/issues/402) and [here](https://blog.ethereum.org/2017/10/12/byzantium-hf-announcement/)) `require(...)` translates to the `REVERT` opcode when it fails, which, before Byzantium, was an invalid opcode.

What version of testrpc are you using? I'm on Ganache CLI v6.0.3.

Will update the package.json file to specify this more precisely.

**Comment by 7flash** [comment]
Thanks for the explanation!

**Pull request closed without merging**
